AZURE_OPENAI_API_KEY: "28e63f0807414e349146b245e4b13d19"
AZURE_ENDPOINT: "https://azure-eastus2-lseg.openai.azure.com/"
API_VERSION: "2024-05-01-preview"
ASSISTANT_ID: "asst_keUpQdioXuoVjucPHGxzUsRd"
NEWS: "vs_2D7YoVnnyRa0c62zOdgP13ag"
RESEARCH: "vs_FuX36W7htiKP199iYXGqfPAg"
ds_username: "ZRAI954"
ds_password: "VOCAL596"
